version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports: 
      - "80:80"
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  one:
    environment: 
      - PORT=3000
   
  two:
    # ports:
    #   - '3002:3000'
    environment: 
      - PORT=3000
      
  three:
    # ports:
    #   - '3003:3000'
    environment: 
      - PORT=3000
